# Generated by Django 5.2 on 2025-05-06 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(default='zatím žádné řešení', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('goal', models.TextField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(choices=[('once_a_week', 'jednou týdně'), ('twice_a_week', 'dvakrát týdně'), ('three_times_a_week', 'třikrát týdně'), ('four_times_a_week', 'čtyřikrát týdně'), ('five_times_a_week', 'pětkrát týdně'), ('times_a_week', 'šestkrát týdně'), ('everyday', 'každý den'), ('once_a_month', 'jednou měsíčně')], default='once_a_week', max_length=50)),
                ('target_repetitions', models.IntegerField(default=21)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Nezahájeno'), ('in_progress', 'V procesu'), ('completed', 'Splněno')], default='not_started', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('category', models.ManyToManyField(blank=True, max_length=32, related_name='habits', to='viewer.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to=settings.AUTH_USER_MODEL)),
                ('obstacle', models.ManyToManyField(blank=True, related_name='obstacles', to='viewer.obstacle')),
                ('reward', models.ManyToManyField(blank=True, related_name='rewards', to='viewer.reward')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
