# Generated by Django 5.2 on 2025-05-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
