# Generated by Django 5.2 on 2025-05-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_reward_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
    ]
