# Generated by Django 5.2 on 2025-05-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_habit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='obstacle',
            new_name='obstacles',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='reward',
            new_name='rewards',
        ),
    ]
