# Generated by Django 5.2 on 2025-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('viewer', '0007_image_obstacle_image_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='in_acquired_habit',
            field=models.ManyToManyField(blank=True, related_name='acquired_habit', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='habit',
            name='in_targeted_habit',
            field=models.ManyToManyField(blank=True, related_name='targeted_habit', to='accounts.profile'),
        ),
    ]
